import os
from typing import List, Optional

import torch
from tensordict import TensorDict
from torch.utils.data import Dataset

from datasets import load_dataset, load_from_disk
from ifo.common.transforms.data import DictTransform


class HuggingFaceDataset(Dataset):
    """A dataset that loads data from Hugging Face."""

    def __init__(
        self,
        path: str,
        name: Optional[str] = None,
        split: str = "train",
        cache_dir: Optional[str] = None,
        num_proc: Optional[int] = None,
        block_size: Optional[int] = None,
        columns: Optional[List[str]] = None,
        transform: Optional[DictTransform] = None,
        **kwargs,
    ) -> None:
        """
        Initialize ProcgenDataset.

        Args:
            path (str): Path or name of the dataset.
            name (str, optional): Defining the name of the dataset configuration.
            split (str, optional): Split of the dataset to load. Defaults to "train".
            cache_dir (str, optional): Directory to read/write data.
            num_proc (int, optional): Number of processes to use.
            block_size (int, optional): Block size of the data.
                Data gets an additional temporal dimension if not 1.
            columns (List[str], optional): Columns to load. If None, all columns are loaded.
            transform (Callable, optional): Transform to apply. Requires DictTransform.
            **kwargs: Additional keyword arguments passed to `load_dataset`.
        """
        assert isinstance(transform, (DictTransform, type(None))), "Transforms must be of type DictTransform!"
        self.block_size = block_size if block_size else 0
        self.transform = transform
        self.columns = columns
        # Local (save_to_disk) datasets: when `path` is a directory on disk, load it with
        # `load_from_disk` instead of pulling from the HF Hub. This lets the generator produce a
        # loadable copy locally (layout <root>/<config>/<split>) and training read it directly,
        # skipping the generate -> push -> download round-trip. A repo id (not a local dir) still
        # routes to `load_dataset` unchanged, so existing configs are unaffected.
        if isinstance(path, str) and os.path.isdir(path):
            local_path = path
            for part in (name, split):
                if part and os.path.isdir(os.path.join(local_path, part)):
                    local_path = os.path.join(local_path, part)
            self.data = load_from_disk(local_path)
        else:
            self.data = load_dataset(path=path, name=name, cache_dir=cache_dir, split=split, num_proc=num_proc, **kwargs)
        self.data = self.data.with_format("torch", columns=columns)

    def __len__(self) -> int:
        if self.block_size and self.block_size > 1:
            return len(self.data) - self.block_size + 1
        return len(self.data)

    def __getitems__(self, indices: List[int]) -> TensorDict:
        """Get a batch of items from the dataset.

        Args:
            indices (List[int]): The indices of the items to get.

        Returns:
            TensorDict: A dictionary containing the items' data.
        """
        assert isinstance(indices, list) and isinstance(indices[0], int), "Indices must be a list of integers"
        if self.block_size:
            indices = torch.as_tensor(indices)[:, None] + torch.arange(self.block_size)[None, :]
            samples = self.data[indices.flatten()]
            samples = TensorDict(samples, batch_size=(len(indices) * self.block_size,))
            samples = samples.view(
                len(indices),
                self.block_size,
            )
        else:
            samples = self.data[indices]
            samples = TensorDict(samples, batch_size=(len(indices),))
        if self.transform:
            samples = self.transform(samples)
        return samples

    def __getitem__(self, index: int) -> TensorDict:
        """
        Get the item at the specified index and return a copy.

        Args:
            index (int): The index of the item to get.

        Returns:
            TensorDict: A dictionary containing the item's data.
        """
        assert isinstance(index, int), "Index must be an integer"
        if self.block_size and self.block_size > 1:
            data = self.data[index : index + self.block_size]
            sample = TensorDict(data, batch_size=(self.block_size,))
        else:
            data = self.data[index]
            sample = TensorDict(data, batch_size=())
        if self.transform:
            sample = self.transform(sample)
        return sample


class ProcgenDataset(HuggingFaceDataset):
    """
    A dataset containing expert trajectories from the Procgen Benchmark environments.

    This dataset contains expert trajectories generated by a PPO reinforcement learning agent trained on each of the
    16 procedurally-generated gym environments from the Procgen Benchmark. The environments were created on
    distribution_mode=easy and with unlimited levels.

    Each data instance represents a single step consisting of tuples of the form:
    (observation, action, reward, terminated, truncated) = (o_t, a_t, r_t, terminated_t, truncated_t)

    The dataset is divided into train (90%) and test (10%) splits,
    with each environment-dataset containing 10M total steps.

    Available environments:
    - bigfish
    - bossfight
    - caveflyer
    - chaser
    - climber
    - coinrun
    - dodgeball
    - fruitbot
    - heist
    - jumper
    - leaper
    - maze
    - miner
    - ninja
    - plunder
    - starpilot

    Data Fields:
    - observation: The current RGB observation from the environment.
    - action: The action predicted by the agent for the current observation.
    - reward: The received reward for the current observation.
    - terminated: If the episode has terminated with the current observation.
    - truncated: If the episode is truncated with the current observation.

    The PPO RL agent was trained for 25M steps on each environment and obtained performance metrics that attain
    or surpass the "Easy Difficulty Baseline Results" described in Appendix I of the Procgen Benchmark paper.
    """

    def __init__(
        self,
        path: str = "NOT_WORKING/procgen",
        name: Optional[str] = None,
        split: str = "train",
        cache_dir: Optional[str] = None,
        num_proc: Optional[int] = None,
        block_size: Optional[int] = None,
        columns: Optional[List[str]] = None,
        transform: Optional[DictTransform] = None,
        **kwargs,
    ) -> None:
        """
        Initialize ProcgenDataset.

        Args:
            path (str, optional): Path or name of the dataset. Defaults to "NOT_WORKING/procgen".
            name (str, optional): Defining the name of the dataset configuration.
            split (str, optional): Split of the dataset to load. Defaults to "train".
            cache_dir (str, optional): Directory to read/write data.
            num_proc (int, optional): Number of processes to use.
            block_size (int, optional): Block size of the data.
                Data gets an additional temporal dimension if not 1.
            columns (List[str], optional): Columns to load. If None, all columns are loaded.
            transform (Callable, optional): Transform to apply. Requires DictTransform.
            **kwargs: Additional keyword arguments passed to `load_dataset`.
        """
        super().__init__(
            path=path,
            name=name,
            split=split,
            cache_dir=cache_dir,
            num_proc=num_proc,
            block_size=block_size,
            columns=columns,
            transform=transform,
            **kwargs,
        )


class DeepMindControlSuiteDataset(HuggingFaceDataset):
    """
    A dataset that loads expert trajectories from the Visual DeepMind Control Suite Benchmark.

    Data Fields:
    - observation: The current RGB observation from the environment.
    - action: The action predicted by the agent for the current observation.
    - reward: The received reward for the current observation.
    - terminated: If the episode has terminated with the current observation.
    - truncated: If the episode is truncated with the current observation.

    The Dreamer V3 RL agent was trained for 1M steps on each environment and obtained performance metrics that attain
    or surpass the "Visual Control Curves" described in Appendix Q of the DeepMind Control Suite paper.

    Available Environments:
        - acrobot_swingup
        - cartpole_balance
        - cartpole_balance_sparse
        - cartpole_swingup
        - cartpole_swingup_sparse
        - cheetah_run
        - cup_catch
        - finger_spin
        - finger_turn_easy
        - finger_turn_hard
        - hopper_hop
        - hopper_stand
        - pendulum_swingup
        - quadruped_run
        - quadruped_walk
        - reacher_easy
        - reacher_hard
        - walker_run
        - walker_stand
        - walker_walk

    Data Splits:
        - train: 9,000,000 steps (90%)
        - test: 1,000,000 steps (10%)
    """

    def __init__(
        self,
        path: str = "NOT_WORKING/visual_dm_control",
        name: Optional[str] = None,
        split: str = "train",
        cache_dir: Optional[str] = None,
        num_proc: Optional[int] = None,
        block_size: Optional[int] = None,
        columns: Optional[List[str]] = None,
        transform: Optional[DictTransform] = None,
        **kwargs,
    ) -> None:
        """
        Initialize DeepMindControlSuiteDataset.

        Args:
            path (str, optional): Path or name of the dataset. Defaults to "NOT_WORKING/visual_dm_control".
            name (str, optional): Defining the name of the dataset configuration (e.g., "acrobot_swingup").
            split (str, optional): Split of the dataset to load. Defaults to "train".
            cache_dir (str, optional): Directory to read/write data.
            num_proc (int, optional): Number of processes to use.
            block_size (int, optional): Block size of the data.
                Data gets an additional temporal dimension if not 1.
            columns (List[str], optional): Columns to load. If None, all columns are loaded.
            transform (Callable, optional): Transform to apply. Requires DictTransform.
            **kwargs: Additional keyword arguments passed to `load_dataset`.
        """
        super().__init__(
            path=path,
            name=name,
            split=split,
            cache_dir=cache_dir,
            num_proc=num_proc,
            block_size=block_size,
            columns=columns,
            transform=transform,
            **kwargs,
        )

class MaskedDistractingControlSuiteDataset(DeepMindControlSuiteDataset):
    """
   This dataset contains expert trajectories generated by a Proximal Policy Optimization (PPO)
   reinforcement learning agent trained on 4 environments of the Distracting Control Suite.
   For each environment we collect data with different levels of distraction, which we define below,
   and masks for the agent.

    Levels of Distraction:
        None: Vanilla DeepMind Control Suite without visual distractions. The environment uses
              the default static background and maintains a fixed camera position.

        Low: Dynamic background distractors only.
             - Background: Video frames from the DAVIS dataset are played sequentially. At each
               step, the background advances to the next frame, cycling through the video
               (direction reverses at endpoints).
             - Camera: Dynamic during an episode, changes position, rotation, and zoom, with distractor magnitude 0.1

        Hard: Both distraction types combined:
             - Background: Same dynamic video background as "Low" level.
             - Camera: Dynamic during an episode, changes position, rotation, and zoom, with distractor magnitude 0.3


    Data Fields:
    - observation: The current RGB observation from the environment.
    - mask: A segmentation mask of the agent, with everything zero, except the agent, which is 255.
    - action: The action predicted by the agent for the current observation.
    - state: The current state of the environment.
    - reward: The received reward for the current observation.
    - terminated: If the episode has terminated with the current observation.
    - truncated: If the episode is truncated with the current observation.

    Available Environments:
        - cheetah_run
        - cheetah_run_distractor_low
        - cheetah_run_distractor_hard

        - hopper_hop
        - hopper_hop_distractor_low
        - hopper_hop_distractor_hard

        - humanoid_walk
        - humanoid_walk_distractor_low
        - humanoid_walk_distractor_hard

        - walker_run
        - walker_run_distractor_low
        - walker_run_distractor_hard

    Data Splits:
        - train: 9,000,000 steps (90%)
        - test: 1,000,000 steps (10%)
    """

    def __init__(
        self,
        path: str = "EpicPinkPenguin/visual_distracting_control_suite",
        name: Optional[str] = None,
        split: str = "train",
        cache_dir: Optional[str] = None,
        num_proc: Optional[int] = None,
        block_size: Optional[int] = None,
        columns: Optional[List[str]] = None,
        transform: Optional[DictTransform] = None,
        use_sam_mask: bool = False,
        **kwargs,
    ) -> None:
        """
        Initialize DeepMindControlSuiteDataset.

        Args:
            path (str, optional): Path or name of the dataset. Defaults to "EpicPinkPenguin/visual_distracting_control_suite".
            name (str, optional): Defining the name of the dataset configuration (e.g., "acrobot_swingup").
            split (str, optional): Split of the dataset to load. Defaults to "train".
            cache_dir (str, optional): Directory to read/write data.
            num_proc (int, optional): Number of processes to use.
            block_size (int, optional): Block size of the data.
                Data gets an additional temporal dimension if not 1.
            columns (List[str], optional): Columns to load. If None, all columns are loaded.
            transform (Callable, optional): Transform to apply. Requires DictTransform.
            use_sam_mask (bool, optional): If True, use the SAM mask instead of the ground truth mask. Defaults to False.
            **kwargs: Additional keyword arguments passed to `load_dataset`.
        """

        super().__init__(
            path=path,
            name=name,
            split=split,
            cache_dir=cache_dir,
            num_proc=num_proc,
            block_size=block_size,
            columns=columns,
            transform=transform,
            **kwargs,
        )

        assert "mask" in self.data.column_names, (
            "SegmentationDataset requires a 'mask' column, "
            f"but got {self.data.column_names}"
        )

        if use_sam_mask:
            self.data = self.data.remove_columns("mask")
            self.data = self.data.rename_column("pred_mask", "mask")
            # Re-apply the torch format after column operations: HuggingFace caches the column
            # mapping internally, so without this the renamed column won't be found at access time.
            self.data = self.data.with_format("torch", columns=self.columns)


class MetaWorldDataset(HuggingFaceDataset):
    """
    A dataset containing expert trajectories for Meta-World, a benchmark for
    meta-reinforcement learning and multi-task learning consisting of 4 distinct
    robotic manipulation tasks. The trajectories were generated using the built-in
    scripted policies (experts) provided by the benchmark.

    Levels of Distraction:
        Dynamic background distractors only.
            - Background: Video frames from the DAVIS dataset are played sequentially. At each
              step, the background advances to the next frame, cycling through the video
              (direction reverses at endpoints).
            - Camera: Not dynamic during an episode, fixed position with no scale or rotation changes.

    Data Fields:
    - observation: The current RGB observation from the environment.
    - mask: A segmentation mask of the agent, with everything zero, except the agent, which is 255.
    - action: The action predicted by the agent for the current observation.
    - state: The current state of the environment.
    - reward: The received reward for the current observation.
    - terminated: If the episode has terminated with the current observation.
    - truncated: If the episode is truncated with the current observation.

    Data Splits:
        - train: 1,000,000 steps (91%)
        - test: 100,000 steps (9%)

    Note:
        If ``name`` contains ``\"distracting\"`` or ``\"masked\"`` and an
        ``observation_distracted`` column is present, this column is used as the
        ``observation`` field (replacing the original ``observation`` column).
    """

    def __init__(
        self,
        path: str = "EpicPinkPenguin/visual_distracting_metaworld",
        name: Optional[str] = None,
        split: str = "train",
        cache_dir: Optional[str] = None,
        num_proc: Optional[int] = None,
        block_size: Optional[int] = None,
        columns: Optional[List[str]] = None,
        transform: Optional[DictTransform] = None,
        use_distracted_obs: bool = False,
        use_sam_mask: bool = False,
        **kwargs,
    ) -> None:
        """
        Initialize DistractingMetaWorldDataset.

        Args:
            path (str, optional): Path or name of the dataset. Defaults to "EpicPinkPenguin/visual_distracting_metaworld".
            name (str, optional): Defining the name of the dataset configuration (e.g., "hammer-v3").
                Must be the bare HuggingFace config name (e.g. "basketball-v3"), without any
                ``"masked-"`` or ``"distracting-"`` prefix, since those don't exist on HuggingFace.
            split (str, optional): Split of the dataset to load. Defaults to "train".
            cache_dir (str, optional): Directory to read/write data.
            num_proc (int, optional): Number of processes to use.
            block_size (int, optional): Block size of the data.
                Data gets an additional temporal dimension if not 1.
            columns (List[str], optional): Columns to load. If None, all columns are loaded.
            transform (Callable, optional): Transform to apply. Requires DictTransform.
            use_distracted_obs (bool, optional): If True, the ``observation_distracted`` column
                replaces the vanilla ``observation`` column. Set this when loading data for a
                ``distracting`` or ``masked`` environment variant. Defaults to False.
            use_sam_mask (bool, optional): If True, use the SAM mask instead of the ground truth mask. Defaults to False.
            **kwargs: Additional keyword arguments passed to `load_dataset`.
        """

        super().__init__(
            path=path,
            name=name,
            split=split,
            cache_dir=cache_dir,
            num_proc=num_proc,
            block_size=block_size,
            columns=columns,
            transform=transform,
            **kwargs,
        )

        assert "mask" in self.data.column_names, (
            "SegmentationDataset requires a 'mask' column, "
            f"but got {self.data.column_names}"
        )

        # Rename observation_distracted -> observation when using a distracting/masked variant.
        # NOTE: `name` is always the bare HF config name (no "masked-"/"distracting-" prefix),
        # so we rely on the explicit `use_distracted_obs` flag instead of inspecting `name`.
        if use_distracted_obs and "observation_distracted" in self.data.column_names:
            self.data = self.data.remove_columns("observation")
            self.data = self.data.rename_column("observation_distracted", "observation")
            # Re-apply the torch format after column operations: HuggingFace caches the column
            # mapping internally, so without this the renamed column won't be found at access time.
            self.data = self.data.with_format("torch", columns=self.columns)

        if use_sam_mask:
            self.data = self.data.remove_columns("mask")
            mask_name = "pred_mask_distracted" if use_distracted_obs else "pred_mask"
            self.data = self.data.rename_column(mask_name, "mask")
            # Re-apply the torch format after column operations: HuggingFace caches the column
            # mapping internally, so without this the renamed column won't be found at access time.
            self.data = self.data.with_format("torch", columns=self.columns)
